[project]
name = "backupd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic>=2.11.3",
    "toml>=0.10.2",
]

[project.scripts]
backupd = "backupd:main"
