[from]
location = "/etc/ssh"
type = "directory"

[to]
backend = "restic"
location = "rclone:gdrive:/backup"
#
# [[hooks.success]]
# cmd = "echo 123"
#
# [[hooks.success]]
# cmd = "echo qwerty"
#
# [[hooks.failure]]
# cmd = "echo 321"
#
# [[hooks.failure]]
# cmd = "echo ytrewq"
