[backup]
type = "directory"
from = "/etc/ssh"

[backend]
to = "rclone:gdrive:/backup"
key = "testkeyhere"

[[hooks.success]]
cmd = "echo 123"

[[hooks.success]]
cmd = "echo qwerty"

[[hooks.failure]]
cmd = "echo 321"

[[hooks.failure]]
cmd = "echo ytrewq"
