where = "/home/le0/.ssh"

# [repo.file]
# name = "./s/a.toml"

[repo.keepass]
name = "repos.kdbx"
passcmd = "echo -n 'redacted'"
entry = "test"

[[hooks.success]]
cmd = "echo 123 > ~/Documents/haskell/backupd/resutl"

[[hooks.success]]
cmd = "echo qwerty"

[[hooks.failure]]
cmd = "echo 321"

[[hooks.failure]]
cmd = "echo ytrewq"
